dist: jammy
language: python
python:
  - 3.8
  - 3.9
  - 3.10
  - 3.11
install:
  - pip install -r base_requirements.txt
  - pip install -U setuptools
  - pip install -U pytest pytest-cov coveralls flake8
  - pip install flask
script:
  - flake8 .
  - python -m pytest --cov .
after_success:
  - coveralls
